[[server]]
name = "docker-carbon-internal"
[server.config]
address = "https://periphery:8120"
enabled = true

##

[[stack]]
name = "pelican"
[stack.config]
server = "docker-carbon-internal"
git_account = "LukeHallett"
repo = "LukeHallett/homelab"
run_directory = "komodo/stacks/docker-carbon-internal/pelican"

##

[[stack]]
name = "wiki"
[stack.config]
server = "docker-carbon-internal"
repo = "LukeHallett/homelab"
run_directory = "komodo/stacks/docker-carbon-internal/wiki"

##

[[resource_sync]]
name = "config"
[resource_sync.config]
repo = "LukeHallett/homelab"
git_account = "LukeHallett"
resource_path = [
  "komodo/controller/resources/main.toml"
]
managed = true
delete = true