services:
  panel:
    image: ghcr.io/pelican-dev/panel:latest
    container_name: pelican_panel
    restart: always
    networks:
      - pelican
    ports:
      - "5022:5022"
    volumes:
      - pelican-data:/pelican-data
      - pelican-logs:/var/www/html/storage/logs
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - XDG_DATA_HOME=/pelican-data
      - APP_URL="https://pelican.lukeh.nz"
      - ADMIN_EMAIL="me@lukeh.nz"

  redis:
    image: redis
    container_name: pelican_redis
    restart: always
    networks:
      - pelican

volumes:
  pelican-data:
    name: pelican-data
  pelican-logs:
    name: pelican-logs

networks:
  pelican:
    name: pelican
